version: "3.8"

services:

  ml-model-api:
    build:
      context: .
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        BUCKET: ${BUCKET}
        ARTIFACT_STORE: ${ARTIFACT_STORE}
        MLFLOW_URI: ${MLFLOW_URI}
        MODEL_NAME: ${MODEL_NAME}
    networks: 
      - main-overlay-network
    # volumes:
    #   - type: bind
    #     source: ./app
    #     target: /opt/ml-model-api/app
    container_name: ml-model-api
    ports:
      - 80:8000
    env_file:
      - ./.env
    restart: always


networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true